inherit_gem:
  bixby: bixby_default.yml

AllCops:
    TargetRubyVersion: 2.5
    Exclude:
        - 'bin/**/*'
        - 'db/**/*'
        - 'tmp/**/*'
        - 'vendor/**/*'
        - 'node_modules/**/*'

Metrics/ClassLength:
    Exclude:
        - 'app/models/marc_indexer.rb'

Metrics/AbcSize:
    Exclude:
        - 'app/models/marc_indexer.rb'
        - 'lib/tasks/sample_scheduler.rake'

Metrics/BlockLength:
    Exclude:
        - app/controllers/catalog_controller.rb
        - spec/controllers/catalog_controller_spec.rb
        - spec/models/user_spec.rb

Metrics/CyclomaticComplexity:
    Exclude:
        - 'app/models/marc_indexer.rb'

Metrics/MethodLength:
    Exclude:
        - 'app/models/marc_indexer.rb'
        - 'lib/tasks/sample_scheduler.rake'

Metrics/PerceivedComplexity:
    Exclude:
        - 'app/models/marc_indexer.rb'

Lint/EmptyWhen:
    Exclude:
        - app/models/marc_indexer.rb