title_addl_tesim: 'Full Title'
title_series_ssim: 'Series Titles'
title_added_entry_tesim: 'Related/Included Titles'
title_varying_tesim: 'Variant Titles'
title_abbr_tesim: 'Abbreviated Titles'
title_translation_tesim: 'Translated Titles'